"""
Deep Learning Model Configuration
Auto-generated by setup_pretrained_model.py
"""

DL_MODEL_CONFIG = {
    'model_path': '/Users/hasanov_avazbek/Desktop/Projects/Study/endoscopic-iqa-project/models/pretrained/mobilenet_v2_iqa.pth',
    'model_type': 'mobilenet_v2' if 'mobilenet' in '/Users/hasanov_avazbek/Desktop/Projects/Study/endoscopic-iqa-project/models/pretrained/mobilenet_v2_iqa.pth' else 'resnet18',
    'input_size': (224, 224),
    'pretrained': True,
    'device': 'auto'  # 'cpu', 'cuda', or 'auto'
}
