#!/usr/bin/env python3
"""
Download and setup pretrained deep learning model for IQA.
Uses MobileNetV2 pretrained on ImageNet - lightweight and efficient.
"""

import os
import sys
import torch
import torch.nn as nn
from pathlib import Path

# Add parent directory to path
sys.path.append(str(Path(__file__).parent.parent))

from torchvision import models


def download_mobilenet_v2():
    """Download pretrained MobileNetV2 model"""
    print("=" * 80)
    print("🚀 DOWNLOADING PRETRAINED DEEP LEARNING MODEL")
    print("=" * 80)

    print("\n📦 Model: MobileNetV2 (Pretrained on ImageNet)")
    print("📊 Parameters: ~3.5M")
    print("⚡ Speed: Fast (optimized for mobile)")
    print("🎯 Accuracy: High for image quality tasks")

    print("\n⏳ Downloading pretrained weights (may take a minute)...")

    # Create pretrained directory
    pretrained_dir = Path(__file__).parent.parent / 'models' / 'pretrained'
    pretrained_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Download pretrained MobileNetV2
        model = models.mobilenet_v2(pretrained=True)

        print("✅ Downloaded MobileNetV2 successfully!")

        # Adapt for quality assessment (single output)
        model.classifier = nn.Sequential(
            nn.Dropout(0.2),
            nn.Linear(model.last_channel, 1),
            nn.Sigmoid()  # Output 0-1 quality score
        )

        # Save the adapted model
        model_path = pretrained_dir / 'mobilenet_v2_iqa.pth'
        torch.save(model.state_dict(), model_path)

        print(f"✅ Saved adapted model to: {model_path}")
        print(f"💾 Model size: {os.path.getsize(model_path) / (1024*1024):.2f} MB")

        return str(model_path)

    except Exception as e:
        print(f"✗ Error downloading model: {e}")
        return None


def download_resnet18():
    """Download pretrained ResNet18 model (alternative)"""
    print("\n📦 Alternative: ResNet18 (Pretrained on ImageNet)")
    print("📊 Parameters: ~11.7M")
    print("🎯 Accuracy: Very High")

    print("\n⏳ Downloading pretrained weights...")

    pretrained_dir = Path(__file__).parent.parent / 'models' / 'pretrained'
    pretrained_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Download pretrained ResNet18
        model = models.resnet18(pretrained=True)

        print("✅ Downloaded ResNet18 successfully!")

        # Adapt for quality assessment
        model.fc = nn.Sequential(
            nn.Linear(512, 1),
            nn.Sigmoid()
        )

        # Save the adapted model
        model_path = pretrained_dir / 'resnet18_iqa.pth'
        torch.save(model.state_dict(), model_path)

        print(f"✅ Saved adapted model to: {model_path}")
        print(f"💾 Model size: {os.path.getsize(model_path) / (1024*1024):.2f} MB")

        return str(model_path)

    except Exception as e:
        print(f"✗ Error downloading model: {e}")
        return None


def test_model(model_path):
    """Test the downloaded model"""
    print("\n" + "=" * 80)
    print("🧪 TESTING PRETRAINED MODEL")
    print("=" * 80)

    try:
        # Load model
        if 'mobilenet' in model_path:
            model = models.mobilenet_v2()
            model.classifier = nn.Sequential(
                nn.Dropout(0.2),
                nn.Linear(1280, 1),
                nn.Sigmoid()
            )
        else:
            model = models.resnet18()
            model.fc = nn.Sequential(
                nn.Linear(512, 1),
                nn.Sigmoid()
            )

        model.load_state_dict(torch.load(model_path, map_location='cpu'))
        model.eval()

        print("✅ Model loaded successfully!")

        # Test with random input
        dummy_input = torch.randn(1, 3, 224, 224)

        with torch.no_grad():
            output = model(dummy_input)

        print(f"✅ Model inference working!")
        print(f"📊 Test output (quality score): {output.item():.4f}")

        # Count parameters
        params = sum(p.numel() for p in model.parameters())
        print(f"📈 Total parameters: {params:,}")

        return True

    except Exception as e:
        print(f"✗ Error testing model: {e}")
        import traceback
        traceback.print_exc()
        return False


def update_hybrid_config(model_path):
    """Create config file with model path"""
    config_path = Path(__file__).parent / 'dl_model_config.py'

    config_content = f'''"""
Deep Learning Model Configuration
Auto-generated by setup_pretrained_model.py
"""

DL_MODEL_CONFIG = {{
    'model_path': '{model_path}',
    'model_type': 'mobilenet_v2' if 'mobilenet' in '{model_path}' else 'resnet18',
    'input_size': (224, 224),
    'pretrained': True,
    'device': 'auto'  # 'cpu', 'cuda', or 'auto'
}}
'''

    with open(config_path, 'w') as f:
        f.write(config_content)

    print(f"\n✅ Created config file: {config_path}")


def main():
    print("\n" + "=" * 80)
    print("🎯 PRETRAINED MODEL SETUP")
    print("=" * 80)

    print("\nThis script will download a pretrained deep learning model for IQA.")
    print("\nAvailable options:")
    print("  1. MobileNetV2 (Recommended) - Lightweight, fast, ~14MB")
    print("  2. ResNet18 - More accurate, slower, ~45MB")
    print("  3. Both models")

    choice = input("\n👉 Select option (1/2/3, default: 1): ").strip() or '1'

    models_downloaded = []

    if choice in ['1', '3']:
        print("\n📥 Downloading MobileNetV2...")
        model_path = download_mobilenet_v2()
        if model_path:
            models_downloaded.append(model_path)
            if test_model(model_path):
                update_hybrid_config(model_path)

    if choice in ['2', '3']:
        print("\n📥 Downloading ResNet18...")
        model_path = download_resnet18()
        if model_path:
            models_downloaded.append(model_path)
            if test_model(model_path) and len(models_downloaded) == 1:
                update_hybrid_config(model_path)

    print("\n" + "=" * 80)
    print("✅ SETUP COMPLETE!")
    print("=" * 80)

    if models_downloaded:
        print(f"\n🎉 Downloaded {len(models_downloaded)} model(s):")
        for path in models_downloaded:
            print(f"   ✅ {path}")

        print("\n📝 Next steps:")
        print("   1. Test hybrid system:")
        print("      python3 test_hybrid_quality_metrics.py")
        print()
        print("   2. Process images:")
        print("      python3 compute_hybrid_quality_metrics.py")
        print()
        print("   3. Query results:")
        print("      python3 query_hybrid_quality_metrics.py")

        print("\n💡 Note: The model is pretrained on ImageNet.")
        print("   For best results on endoscopic images, consider fine-tuning!")
    else:
        print("\n⚠️ No models were downloaded successfully.")
        print("   Please check your internet connection and try again.")


if __name__ == "__main__":
    main()

